### ISSUE TITLE
Debugger of NodeJs stopped working after upgrade to 17.0 and latr

### ISSUE THREAD

**Issue by oleksiizozulenko** [maximehamm/tzatziki#74]
When I update plugin to version 17.0.0  I was not able to debug my nodejs project. 
Debugger crashed with error 
Cannot invoke (class=, method=processStarted, topic=XDebuggerManager events)

I'm using npm run command for start debug process. 
WebStorm 2023.3.6
Build #WS-233.15026.13, built on March 21, 2024
Licensed to Oleksii Zozulenko
Subscription is active until April 5, 2024.
Runtime version: 17.0.10+1-b1087.23 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (233.15026.16)
  com.intellij.properties (233.11799.172)
  io.nimbly.tzatziki (17.0.0)
  com.intellij.ml.llm (233.15026.24)
  izhangzhihao.rainbow.brackets (2024.2.2-233)

**Comment by oleksiizozulenko** [comment]
Also IDE notify error
Unhandled exception in [CoroutineName(com.intellij.xdebugger.impl.XDebuggerManagerImpl), StandaloneCoroutine{Cancelling}@5a9cf638, Dispatchers.Default]

java.lang.NoClassDefFoundError: org/jetbrains/kotlin/idea/editor/fixers/FixersUtilKt
	at io.nimbly.tzatziki.util.DocumentUtilsKt.shrink(DocumentUtils.kt:46)
	at io.nimbly.tzatziki.breakpoints.TzStepBreakpointType.canPutAt(TzStepBreakpointType.kt:25)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointUtil.getAvailableLineBreakpointInfo(XBreakpointUtil.java:209)
	at com.intellij.xdebugger.impl.breakpoints.XBreakpointUtil.getAvailableLineBreakpointTypes(XBreakpointUtil.java:161)
	at com.intellij.xdebugger.impl.XDebuggerLineChangeIconProvider$getIcon$2$1.invoke(XDebuggerLineChangeHandler.kt:64)
	at com.intellij.xdebugger.impl.XDebuggerLineChangeIconProvider$getIcon$2$1.invoke(XDebuggerLineChangeHandler.kt:63)
	at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator$lambda$1(coroutines.kt:454)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.CoroutinesKt.jobToIndicator(coroutines.kt:442)
	at com.intellij.openapi.progress.CoroutinesKt.contextToIndicator(coroutines.kt:414)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextToIndicator(coroutines.kt:402)
	at com.intellij.xdebugger.impl.XDebuggerLineChangeIconProvider$getIcon$2.invoke(XDebuggerLineChangeHandler.kt:63)
	at com.intellij.xdebugger.impl.XDebuggerLineChangeIconProvider$getIcon$2.invoke(XDebuggerLineChangeHandler.kt:62)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:108)
	at com.intellij.openapi.application.rw.InternalReadAction.access$insideReadAction(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:95)
	at com.intellij.openapi.application.rw.InternalReadAction$tryReadCancellable$2.invoke(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1$lambda$0(cancellableReadAction.kt:38)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke$lambda$1(cancellableReadAction.kt:36)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.application.rw.CancellableReadActionKt$cancellableReadActionInternal$1.invoke(cancellableReadAction.kt:34)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:310)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:31)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:94)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:78)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:65)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invokeSuspend(InternalReadAction.kt:44)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$4.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:40)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:58)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:25)
	at com.intellij.xdebugger.impl.XDebuggerLineChangeIconProvider.getIcon$suspendImpl(XDebuggerLineChangeHandler.kt:62)
	at com.intellij.xdebugger.impl.XDebuggerLineChangeIconProvider.getIcon(XDebuggerLineChangeHandler.kt)
	at com.intellij.xdebugger.impl.XDebuggerLineChangeHandler$1$1.invokeSuspend(XDebuggerLineChangeHandler.kt:34)
	at com.intellij.xdebugger.impl.XDebuggerLineChangeHandler$1$1.invoke(XDebuggerLineChangeHandler.kt)
	at com.intellij.xdebugger.impl.XDebuggerLineChangeHandler$1$1.invoke(XDebuggerLineChangeHandler.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:217)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:382)
	at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(SharedFlow.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(com.intellij.xdebugger.impl.XDebuggerManagerImpl), StandaloneCoroutine{Cancelled}@5a9cf638, Dispatchers.Default]
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.idea.editor.fixers.FixersUtilKt PluginClassLoader(plugin=PluginDescriptor(name=Cucumber +, id=io.nimbly.tzatziki, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/WebStorm2023.3/plugins/plugin-tzatziki, version=17.0.0, package=null, isBundled=false), packagePrefix=null, state=active)
	... 76 more

**Comment by maximehamm** [comment]
Please can you test with version 17.1.1 or above ? I think I was fixing this last week...
Thank you for your feedback

**Comment by oleksiizozulenko** [comment]
I have found this error when updated to latest version 17.1.1 and after that investigated that it appeared since 17.0.0

**Comment by drussilla** [comment]
The same error is popping up in Rider 2023.4 with Cucumber+ 17.1.2. Disabling plugin helped.

**Comment by maximehamm** [comment]
I removed the use of "org/jetbrains/kotlin/idea/editor/fixers/FixersUtilKt" then the stack trace should be slightly different...
Please send me a new stack trace...

**Comment by oleksiizozulenko** [comment]
Update to 17.2.0 - looks issue is resolved

**Comment by maximehamm** [comment]
I will close this issue then ! 
Please add a review at IntelliJ market place ;)
